-- SQLite

-- Tarefa 17


SELECT EMPLOYEES.ID AS 'Código', 
       EMPLOYEES.NAME AS 'Nome', 
       EMPLOYEES.PHONE_NUMBER AS 'Número de Celular', 
       EMPLOYEES.CONTRACT_DATE AS 'Data do Contrato',
       POSITIONS.DESCRIPTION AS 'Cargo' 
  FROM EMPLOYEES JOIN POSITIONS 
  ON (EMPLOYEES.POSITION_ID = POSITIONS.ID);