-- SQLite

-- Tarefa 18


SELECT EMPLOYEE_ID
    FROM LOCATIONS
    GROUP BY EMPLOYEE_ID
    HAVING COUNT(EMPLOYEE_ID) >= 2;

SELECT E.NAME AS 'Nome' FROM EMPLOYEES  AS E
    JOIN (SELECT EMPLOYEE_ID
          FROM LOCATIONS
          GROUP BY EMPLOYEE_ID
          HAVING COUNT(EMPLOYEE_ID) >= 2)
    AS W
    ON E.ID = W.EMPLOYEE_ID;

