-- SQLite

-- Tarefa 19


SELECT CUSTOMER_ID FROM LOCATIONS 
  GROUP BY CUSTOMER_ID
  HAVING COUNT(CUSTOMER_ID) >= 2;


SELECT C.NAME AS 'Nome' FROM CUSTOMERS AS C
  JOIN (SELECT CUSTOMER_ID FROM LOCATIONS 
        GROUP BY CUSTOMER_ID
        HAVING COUNT(CUSTOMER_ID) >= 2) 
  AS W
  ON C.ID = W.CUSTOMER_ID;